// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Auto-generate sidebar from docs folder structure
    },
  ],
};

module.exports = sidebars;